MYROBOT:
# Publish joint_states
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  # Position Controllers
  my_controller_joint_0:
    type: my_controller/MyPositionController
    joint: husky_to_robot_base_plate
    gain: 50.1

  my_controller_joint_1:
    type: my_controller/MyPositionController
    joint: joint_1
    gain: 150.1

  my_controller_joint_2:
    type: my_controller/MyPositionController
    joint: joint_2
    gain: 150.1

  my_controller_joint_3:
    type: my_controller/MyPositionController
    joint: joint_3
    gain: 150.1
  my_controller_joint_4:
    type: my_controller/MyPositionController
    joint: joint_4
    gain: 150.1
  my_controller_joint_5:
    type: my_controller/MyPositionController
    joint: joint_5
    gain: 150.1
  my_controller_joint_6:
    type: my_controller/MyPositionController
    joint: joint_6
    gain: 150.1
